package client;

public class LanguageTemplate {

    public static final String TEMPLATE = """
            other=
            return=
            expenses=
            user=
            add=
            edit=
            Create new event=
            Join event=
            All your events=
            create=
            join=
            delete=
            Select User=
            allTags=
            noTag=
            travel=
            Show all=
            From user=
            Including user=
            date=
            description=
            tag=
            amount=
            Submit tag=
            Send invite=
            Show stats=
            Select or create tag=
            Select Color=
            Select tag=
            Add expense=
            Settle debt=
            title=
            settings=
            language=
            Signed in as=
            New language input=
            Add language=
            dictionary=
            continue=
            Total amount=
            Delete expense=
            confirm=
            cancel=
            entrance_fees=
            Total cost=
            Click on slice to see values=
            Who Paid=
            What For=
            Split between who=
            Split equal=
            Add/edit expense=
            owes=
            owes amount=
            Yes, with total amount=
            Needs to be filled in=
            save=
            food=
            Red=
            Green=
            Blue=
            Orange=
            Yellow=
            Purple=
            Pink=
            Cyan=
            Black=
            Brown=
            Gray=
            Invite code=
            Confirm expense deletion=
            No expenses available=
            Add/edit participants of the event=
            Participants of the event=
            Add users that are available on the server=
            Remove from event=
            Enter password=
            Incorrect password=
            Username=
            Admin Login=
            Please enter your information=
            Email=
            Original Payer=
            Paid=
            Category=
            Give people the following invite code=
            Invite the following people by email=
            One address per line=
            In this format=
            Send invites=
            Amount=
            The title cannot be empty=
            Change credentials=
            Add Server Url=
            Server Not Available=
            paid for=
            No color for no tag=
            sort=
            Alphabetically=
            Newest Event=
            Latest Activity=
            Send reminder=
            Remind everyone=
            Part of expense=
            Transactions needed to settle debts=
            Email did not send=
            password=
            Test email=
            event was deleted=
            confirm event removal from list=
            confirm event deletion from database=
            Paid amount=
            amount cannot be empty=
            could not find user with username=
            you have to add at least 1 user as debtor=
            Delete event=
            No events available=
            Settle=
            Filters=
            iban=
            Local information=
            Import json=
            Export json=
            currency=
            No participants=
            Incorrect invite code=
            """;
}
