name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run AggregateJacocoReport
        run: ./gradlew AggregateJacocoReport

      - name: Preserve coverage information
        run: |
          mv build/reports/jacoco/aggregate/html ./coverage
          mv build/reports/jacoco/aggregate/jacocoTestReport.xml ./coverage/report.xml
          echo `cat coverage/index.html | grep -o -E "Total[^%]+?%" | sed -E "s/<.*>//" | sed -E "s/Total/TestCoverage:/"`

      - name: Upload coverage to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./coverage